# Generated by Django 4.0.2 on 2022-02-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityDetails',
            new_name='LocationDetails',
        ),
    ]
